added promises
mate-academy/js_promises_practice_DOM pull request #216
Opened 2022-07-13 10:26 UTC by silchyn

[DEMO](https://silchyn.github.io/js_promises_practice_DOM/)

2022-07-14 06:20 UTC, BudnikOleksii requested changes
Good! You can improve your solution, left a comment😉

2022-07-14 06:20 UTC, BudnikOleksii commented on src/scripts/main.js
> +});
You can do it in one handler by sending 'e.button'  that clicked in the parameter, the same code

2022-07-14 06:40 UTC, BudnikOleksii approved these changes
🔥

2022-07-14 07:13 UTC, ivan-kadykalo requested changes

2022-07-14 07:13 UTC, ivan-kadykalo commented on src/scripts/main.js
> +    e.preventDefault();
Avoid of using one letter names

2022-07-14 14:43 UTC, Ihor-Karpyn approved these changes

2022-12-07 17:00 UTC, ivan-kadykalo approved these changes

2023-02-10 20:10 UTC, closed without merging