solution
mate-academy/js_promises_practice_DOM pull request #5
Opened 2020-10-11 13:35 UTC by b0hdan1

2020-10-12 08:37 UTC, vpolets requested changes

2020-10-12 08:37 UTC, vpolets commented on src/scripts/main.js
> +const forPromise3 = waitFor(rightClick);
але це 2 проміси а не один

2020-10-12 15:26 UTC, vpolets requested changes

2020-10-12 15:26 UTC, vpolets commented on src/scripts/main.js
> +const twoClicks = ['click', 'contextmenu'];
ну тільки це мало бути в середині функції

2020-10-12 15:26 UTC, vpolets commented on src/scripts/main.js
> +      if (twoClicks.length === 1) {
та ну, а чого не 0?

2020-10-12 15:26 UTC, vpolets commented on src/scripts/main.js
> +      }
filter роби, бо так 2 рази правою кнопкою нажму і масив чистий

2020-10-12 17:05 UTC, b0hdan1 commented on src/scripts/main.js
> +      if (twoClicks.length === 1) {
с 0 не правильно работает)

2020-10-14 07:39 UTC, vpolets approved these changes

2024-04-25 17:21 UTC, closed without merging