add solution
mate-academy/js_promises_practice_DOM pull request #639
Opened 2024-03-02 14:38 UTC by dimarogkov

[DEMO LINK](https://dimarogkov.github.io/js_promises_practice_DOM/)

2024-03-02 17:03 UTC, vadiimvooo requested changes
Seems like you haven't add notifications for resolved and rejected promises according to task.
![image](https://github.com/mate-academy/js_promises_practice_DOM/assets/108701488/780349a6-c59b-4c1b-bfca-10e1b54dc8b1)

2024-03-02 17:03 UTC, vadiimvooo commented on src/scripts/main.js
> +    };
```suggestion
    const onClick = (e) => {
      e.preventDefault();
      resolve('Second promise was resolved');
    };
```

2024-03-03 13:06 UTC, Viktor-Kost requested changes

2024-03-03 13:06 UTC, Viktor-Kost commented on src/scripts/main.js
> +document.addEventListener('DOMContentLoaded', () => {
I would recommend to move your resolvers into own functions

```
const clickPromise = new Promise(resolve => {
  document.addEventListener('click', () => {
    resolve();
  });
});


const contextMenuPromise = new Promise(resolve => {
  document.addEventListener('contextmenu', () => {
    resolve();
  });
});
```

apply Promise.race to the secondPromise

```
const secondPromise = new Promise((resolve, reject) => {
  Promise.race([clickPromise, contextMenuPromise])
    .then((value) => resolve('Second promise was resolved'));
});
```


apply Promise.all to the thirdPromise

```
const thirdPromise = new Promise(resolve => {
  Promise.all([clickPromise, contextMenuPromise])
    .then((value) => resolve('Third promise was resolved'));
});
```

2024-03-05 19:02 UTC, loralevitska approved these changes
Well done)

2024-06-28 09:02 UTC, closed without merging